# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-07 05:01
from __future__ import unicode_literals

import ClimbingApp.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ascent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('comments', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='AscentOutcome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('image', models.ImageField(upload_to='ascent_outcome/')),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('inner_r', models.PositiveSmallIntegerField()),
                ('inner_g', models.PositiveSmallIntegerField()),
                ('inner_b', models.PositiveSmallIntegerField()),
                ('outer_r', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('outer_g', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('outer_b', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, upload_to=ClimbingApp.models.color_image_path)),
            ],
        ),
        migrations.CreateModel(
            name='Difficulty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('sort_name', models.SlugField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Gym',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('sort_name', models.SlugField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setDate', models.DateField(default=datetime.date.today)),
                ('removeDate', models.DateField(blank=True, null=True)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ClimbingApp.Color')),
                ('difficulty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ClimbingApp.Difficulty')),
            ],
        ),
        migrations.CreateModel(
            name='Wall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('sort_name', models.SlugField(max_length=32)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='walls', to='ClimbingApp.Gym')),
            ],
        ),
        migrations.AddField(
            model_name='route',
            name='wall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='ClimbingApp.Wall'),
        ),
        migrations.AddField(
            model_name='ascent',
            name='outcome',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ClimbingApp.AscentOutcome'),
        ),
        migrations.AddField(
            model_name='ascent',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ClimbingApp.Route'),
        ),
        migrations.AddField(
            model_name='ascent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
